# Generated by Django 5.2 on 2025-04-10 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('client_type', models.CharField(blank=True, choices=[('KVO', 'KVO'), ('Personal', 'Personal'), ('Other', 'Other')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
