# Generated by Django 5.2 on 2025-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clientdetails_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('eggetarian', 'Eggetarian'), ('nonveg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo')], default='veg', max_length=15, null=True),
        ),
    ]
