# Generated by Django 5.2 on 2025-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientdetails_diet_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='chief_complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
