# Generated by Django 5.2 on 2025-11-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientdetails_chief_complaints_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('workout_type', models.CharField(blank=True, max_length=100, null=True)),
                ('workout_calories', models.PositiveIntegerField(blank=True, help_text='Calories burned during workout', null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours of sleep', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('food_calories', models.PositiveIntegerField(blank=True, help_text='Calories consumed from food', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'DIETICIAN'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_health', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Health Record',
                'verbose_name_plural': 'Daily Health Records',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
