# Generated by Django 5.2 on 2025-11-08 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_dailyhealthrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyhealthrecord',
            unique_together={('user', 'created_at')},
        ),
    ]
