# Generated by Django 5.2 on 2025-11-08 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_dailyhealthrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhealthrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
